Fiorello-Admin-Panel/Fiorello/Models/Product.cs
namespace Fiorello.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Price { get; set; } 
        public Category? Category { get; set; }  
        public int CategoryId { get; set; } 
        public string? ImageUrl { get; set; }   
        public double? DiscountDegree { get; set; } 
    }
}

Fiorello-Admin-Panel/Fiorello/Controllers/ProductController.cs
using Fiorello.DAL;
using Fiorello.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiorello.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _dbContext;
        private int _prductCount;

        public ProductController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
            _prductCount = dbContext.Products.Count();
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.prductCount = _prductCount;

            List<Product> products = await _dbContext.Products
                .Include(p=>p.Category)
                .Take(4)
                .ToListAsync();

            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null) return NotFound();

            Product product = await _dbContext.Products
                .SingleOrDefaultAsync(pId => pId.Id == id);

            if (product == null) return NotFound();

            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Partial(int skip)
        {
            if (skip >= _prductCount)
                return BadRequest();

            List<Product> products = await _dbContext.Products
                .Include(p => p.Category)
                .Skip(skip)
                .Take(4)
                .ToListAsync();

            return PartialView("_ProductPartialView", products);
        }

    }
}

Fiorello-Admin-Panel/Fiorello/ViewComponents/DiscountProductsViewComponent.cs
using Fiorello.DAL;
using Fiorello.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiorello.ViewComponents
{
    public class DiscountProductsViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public DiscountProductsViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Product> products = await _dbContext.Products
                .Where(p => p.DiscountDegree != null)
                .Include(p=>p.Category)
                .ToListAsync();

            return View(products);
        }
    }
}

Fiorello-Admin-Panel/Fiorello/Views/Product/Details.cshtml
@model Fiorello.Models.Product
@{
    Product product = Model;
}
<h1>@product.Name  @product.Price</h1>

Fiorello-Admin-Panel/Fiorello/Views/Product/Index.cshtml
@{
    List<Product> products = Model;
}
<!-- SHOP LIST TITLE START -->
<section id="shop-list-title">
    <div class="container py-4">
        <div class="row py-5">
            <div class="col-12">
                <h1>Shop List</h1>
            </div>
        </div>
    </div>
</section>
<!-- SHOP LIST TITLE END -->

<!-- SHOP LIST START -->
<section id="shop-list">
    <div class="container">
        <div class="row py-5" id="prduct-list">
            <input type="hidden" id="prduct-count" value="@ViewBag.prductCount" />
            <partial name="_ProductPartialView" model="Model" />
        </div>
        <div class="row justify-content-center">
            <button id="load-more" class="btn btn-primary mb-5">Load More</button>
        </div>
    </div>
</section>
<!-- SHOP LIST END -->

<!-- SHOP LIST TITLE START -->
<section id="shop-list-title">
    <div class="container py-4">
        <div class="row py-5">
            <div class="col-12">
                <h1>Discount List</h1>
            </div>
        </div>
    </div>
</section>
<!-- SHOP LIST TITLE END -->
<!-- PRODUCTS START -->
<section id="products">
    <div class="container">
        <div class="row py-5">
            @await Component.InvokeAsync("DiscountProducts")
        </div>
    </div>
</section>
<!-- PRODUCTS END -->